<a href="https://colab.research.google.com/github/arnabbiswasofficial07/hello--world/blob/master/Numpy_Online.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Numpy!

### Pre-requisites for this tutorial : 
* Basics of Python


## What is Numpy?

***numpy*** is a Python library, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. numpy = numeric python.

numpy works under the hood of many packages like pandas, scikit-learn and more. So fundamental understanding of how it works is important to have a hassle free experience with others. Join me in Learning

## Importing package

In [0]:
import numpy as np

np is an object for numpy package. If you don't want, class itself can be used as such.
For eg., you can use, numpy.array()

## Creating Arrays

In [0]:
arr1 = np.array([1,2,3,4,5,6])
print("1D array: ", arr1)
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array: ", "\n",arr2)

1D array:  [1 2 3 4 5 6]
2D array:  
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Understanding attributes of arrays

In [0]:
print("About arr2:")
print("Type\t\t:" ,type(arr2))
print("Datatype\t:",arr2.dtype)
print("Shape\t\t:", arr2.shape)
print("Size\t\t:",arr2.size)
print("itemsize\t:",arr2.itemsize)
print("No. of dim\t:",arr2.ndim)
print("No. of bytes\t:", arr2.nbytes)

About arr2:
Type		: <class 'numpy.ndarray'>
Datatype	: int32
Shape		: (3, 3)
Size		: 9
itemsize	: 4
No. of dim	: 2
No. of bytes	: 36


## Creating Special arrays

In [0]:
arr3 = np.zeros((6,2), dtype=int)
arr4 = np.ones((3,4),dtype=float)
arr5 = np.eye(5,5)
arr6 = np.random.rand(3,2)
arr7 = np.random.randint(7,size=(2,6))
print("Zero Array \t:\n",arr3)
print("Arrays with unit values\t:\n",arr4)
print("Identity matrix\t:\n",arr5)
print("Random array\t\n",arr6)
print("Random integer array\t:\n" , arr7)

Zero Array 	:
 [[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
Arrays with unit values	:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity matrix	:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Random array	
 [[0.25728532 0.65799533]
 [0.49035217 0.73083235]
 [0.74856197 0.83953684]]
Random integer array	:
 [[2 3 5 6 1 1]
 [4 5 4 4 4 5]]


## Creating arrays using "arange")
creates an array having elements from start to stop-1 in step of "step" value.
Interval is known and set by developer(step).

arange(start,stop,step)

In [0]:
arr8 = np.arange(1,10,2)
print("Array created with arange: \t\n",arr8)

Array created with arange: 	
 [1 3 5 7 9]


## Creating arrays using "linspace"
linspace creates an array within the range.
    Number of elements to be created is fixed and the interval between the elements is calculated by the system.
    linspace will include the last value(stop)

In [0]:
arr9 = np.linspace(1,500,5)
print("Array created using linspace requesting 50 elements within 1 to 10:\t\n",arr9)

Array created using linspace requesting 50 elements within 1 to 10:	
 [  1.   125.75 250.5  375.25 500.  ]


## Slicing 

Inside [], the dimensions are seperated by commas.
For eg., arr9[3,4] represents the element in 4th row and 5th column
![image.png](attachment:image.png)

In [0]:
arr10 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(arr10)
print("Row 2:",arr10[1,:])
print("Column 2:",arr10[:,3])
print("Elements 7,8,12,13 :\n", arr10[1:3,1:3])
print("All elements: \n",arr10[::])
print("Strides:\n",arr10[0::2,1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Row 2: [ 6  7  8  9 10]
Column 2: [ 4  9 14 19]
Elements 7,8,12,13 :
 [[ 7  8]
 [12 13]]
All elements: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Strides:
 [[ 2  3]
 [12 13]]


## Masking - Important concept in Image processing

In [0]:
arr11 = np.array([1,2,3,4,5,6,7,8,9])
mask = np.array([0,1,1,0,1,0,1,0,0],dtype=bool)
print(arr11[mask])

[2 3 5 7]


## Some more methods

In [0]:
arr12 = np.array([[1,2,3,4,5],[6,7,8,9,9]])
print(arr12)
print("Sum :\t",np.sum(arr12))
print("Sum :\t",np.sum(arr12,axis=0))
print("Prod :\t",np.prod(arr12))
print("Prod :\t",np.prod(arr12,axis=0))
print("Minimum :\t",np.min(arr12,axis=0))
print("Maximum :\t",np.max(arr12,axis=0))
print("Mean :\t",np.mean(arr12,axis=0))
print("Variance:\t",np.var(arr12,axis=0))
print("Standard Deviation:\t",np.std(arr12,axis=0))
print("Average:\t",np.average(arr12,axis=0))
print("Weighted Average:\t",np.average(arr12,weights=[1,2,3,4,5],axis=1))

[[1 2 3 4 5]
 [6 7 8 9 9]]
Sum :	 54
Sum :	 [ 7  9 11 13 14]
Prod :	 3265920
Prod :	 [ 6 14 24 36 45]
Minimum :	 [1 2 3 4 5]
Maximum :	 [6 7 8 9 9]
Mean :	 [3.5 4.5 5.5 6.5 7. ]
Variance:	 [6.25 6.25 6.25 6.25 4.  ]
Standard Deviation:	 [2.5 2.5 2.5 2.5 2. ]
Average:	 [3.5 4.5 5.5 6.5 7. ]
Weighted Average:	 [3.66666667 8.33333333]


## Scalar Operations - Arithmetic

In [0]:
arr13 = np.array([1,2,3])
arr14 = np.array([4,5,6])
arr15 = arr13+arr14
arr16 = arr13 - arr14
print("Summation:\t",arr15)
print("Difference:\t",arr16)

arr16+=5
print("Previous output after adding 5:",arr16)

###  Try other operations



Summation:	 [5 7 9]
Difference:	 [-3 -3 -3]
Previous output after adding 5: [2 2 2]


## Relational Operations

In [0]:
result1 = arr16 == arr15
print(result1)

### Try other relational operations <<result2 to result6


[False False False]


## Trignometric & Logarithmic operations

In [0]:
arr17 = np.array([15,30,45,90])
result7 = np.sin(arr17)
print("Sin values:\t",result7)
result8 = np.log(arr17)
print("Log value:\t",result8)
result9=np.cos(arr17)
print("Cos values:\t",result9)

### Try other operations

Sin values:	 [ 0.65028784 -0.98803162  0.85090352  0.89399666]
Log value:	 [2.7080502  3.40119738 3.80666249 4.49980967]
Cos values:	 [-0.75968791  0.15425145  0.52532199 -0.44807362]


## Vector operations

### Math - Scalar and Vector

#### Scalar

* np.add(a,1) -> Add 1 to each array element
* np.subtract(a,2) -> Subtract 2 from each array element
* np.multiply(a,3) -> Multiply each array element by 3
* np.divide(a,4) -> Divide each array element by 4 (it returns np.nan for division by zero)
* np.power(a,5) -> Raise each array element to the 5th power

#### Vector Math

* np.add(a1,a2) -> Elementwise add a2 to a1
* np.subtract(a1,a2) -> Elementwise subtract a2 from a1
* np.multiply(a1,a2) -> Elementwise multiply a1 by a2
* np.divide(a1,a2) -> Elementwise divide a1 by a2
* np.power(a1,a2) -> Elementwise raise a1 raised to the power of a2

* np.array_equal(a1,a2) -> Returns True if the arrays have the same elements and shape *(Note - a1 == a2 -> Returns True if the arrays have the same elements)*
* np.sqrt(a) -> Square root of each element in the array
* np.round(a) -> Rounds to the nearest int

In [0]:
#Try them out
a=np.array([1,2,3,4])
np.add(a,1)
#np.power(a,2)

array([2, 3, 4, 5])

### Statistical Analysis

* np.mean(a) -> Returns mean along specific axis
* np.sum(a) -> Returns sum of all values in a
* a.min() -> Returns minimum value of a
* a.max() -> Returns maximum value of specific axis

A few more for you to discover - 
* np.var(a)
* np.std(a)
* arr.corrcoef()

In [0]:
#Try them out
a1=np.array([2,4,6,8])
np.sum(a1)
a1.min()
np.var(a1)

5.0

### Summation for thought - 

Are all these same?

1. sum_value = np.sum(a)
2. columnSum = np.sum(a, axis = 0)
3. rowSum = np.sum(a, axis = 1)

In [0]:
#Try them out
a=np.array([[1,2,3,4],[5,6,7,8]])
s=np.sum(a)
print(s)
cs=np.sum(a,axis=0)
print(cs)
rs=np.sum(a,axis=1)
print(rs)

36
[ 6  8 10 12]
[10 26]


**From the results produced above, the answer is a big...**
# NO


1. Gives sum of all values
2. Gives sum of columns
3. Gives sum of rows

The methods mentioned in Statistics column all have a parameter 'axis'. Try and find out how each time it performs a different function with changing values for 'axis'

## And with that, we wrap up numpy...

![That's all folks! See you in the next topic.](see-you.jpg)